version: "3.7"
services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql-9.0.1
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: 'spam_caller'              # name of database
      MYSQL_USER: 'sample'                # sample is the name of user
      MYSQL_PASSWORD: 'password'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'password'     # password for root user
    ports:
      - '3307:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db: