# Generated by Django 5.1 on 2024-08-25 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["phone_number"], name="users_profi_phone_n_8821cb_idx"
            ),
        ),
    ]
